/* ── i18n Strings ── */
var STRINGS = {
  zh: {
    appName: '复习追踪器', pageTitle: '考试复习追踪器',
    myCourses: '我的课程', addCourse: '添加课程',
    noCoursesTitle: '还没有课程', noCoursesHint: '点击「添加课程」开始规划你的复习计划',
    addCourseTitle: '添加新课程', courseName: '课程名称', courseNamePh: '例：高等数学',
    subjectLabel: '科目分类', subjectPh: '例：数学、英语、物理…',
    examDate: '考试日期', totalChapters: '章节总数', totalChaptersPh: '例：12',
    color: '课程颜色',
    cancel: '取消', add: '添加', addCourseBtn: '添加课程', saveChanges: '保存更改',
    openCourse: '打开课程', deleteCourse: '删除课程',
    noDate: '暂无考试日期', expired: '已过期', examToday: '今天考试！',
    daysLeft: '还有 {n} 天',
    studyProgress: '复习进度', chaptersCount: '{done}/{total} 章节',
    totalCoursesCount: '{n} 门课程', avgProgressText: '平均进度 {n}%',
    courseAdded: '「{name}」已添加 ✓', courseDeleted: '已删除「{name}」',
    backBtn: '← 返回', editInfo: '✎ 编辑信息', importChapters: '+ 导入章节',
    loading: '加载中…',
    totalProgress: '总复习进度',
    noChapters: '暂无章节',
    noChaptersAddHint: '暂无章节 — 请导入或手动添加',
    heroCompleted: '已完成 {done} / {total} 个知识点',
    chapterToc: '章节目录',
    noChaptersImport: '暂无章节 — 点击导入',
    chapMeta: '{n} 章 · {pts} 个知识点',
    secCount: '{n} 个知识点',
    importFromPdfTitle: '从 PDF 导入章节目录',
    importPdfDrag: '将课本 PDF 拖拽到此处，或点击选择文件',
    choosePdf: '选择 PDF 文件',
    manualAdd: '手动添加章节',
    courseMaterials: '课程资料',
    pdfConvert: 'PDF 转换',
    htmlConvert: 'HTML 转换',
    htmlConvertTitle: '上传 HTML 文件，通过 MinerU 转换为 Markdown',
    dragToUpload: '拖拽文件到此处或点击上传',
    importMore: '+ 导入更多',
    noChaptersMore: '暂无章节 — 点击上方「导入更多」',
    expandAll: '展开', collapseAll: '折叠', resetChapters: '重置',
    aiAssistant: 'AI 学习助手', aiSub: '我可以帮你制定复习计划、解答课程疑问、分析重点内容。',
    genPlan: '📋 生成复习计划', summarize: '📖 总结课程重点', quiz: '❓ 出题测验',
    askAI: '向 AI 助手提问…（Enter 发送，Shift+Enter 换行）',
    history: '历史', newChat: '＋ 新对话',
    historyChat: '历史对话', historyBtnTitle: '历史对话',
    aiContextTitle: '可读取的 Markdown 课程资料',
    filesCount: '{n} 个文件',
    tabText: '文字', tabUrl: '链接',
    guidePh: '粘贴老师发的复习提纲、考试重点、题型说明…',
    uploadPdfHint: '上传小型 PDF，AI 将自动提取文字内容',
    clearReselect: '✕ 重新选择', fetchContent: '获取内容', clearUrl: '✕ 清除',
    attachGuide: '附加复习资料',
    aiInputHint: 'AI 可自动读取课程 Markdown 资料 · Enter 发送',
    delConv: '删除',
    importPdfModalTitle: '导入 PDF 目录',
    dropPdfHere: '拖拽 PDF 到此处', orText: '或', chooseFile: '选择文件',
    pdfBookmarkNote: '仅支持含书签目录的 PDF',
    extractingToc: '正在提取目录，请稍候…',
    retrySelect: '重新选择', noBookmarkTitle: '此 PDF 没有书签目录',
    pasteTocLabel: '粘贴目录文本',
    tocPastePh: '例：\nChapter 3 Linear Algebra\n3.1 Vector Spaces\n3.2 Subspaces\n3.3 Linear Independence\nChapter 4 Matrix Operations\n4.1 Matrix Addition',
    parseTocText: '解析文本目录', orUseAI: '或使用 AI 提取',
    mineruDesc: '通过 MinerU 解析 PDF 内容，再由 Gemini 自动生成章节目录结构',
    pdfSizeNote: '（支持 3.5MB 以内的 PDF）',
    aiExtractToc: '🤖 AI 智能提取目录',
    uploadFile: '上传文件', mineruParse: 'MinerU 解析', generateToc: '生成目录',
    preparing: '正在准备…',
    chapterRangeLabel: '描述要导入的章节范围（支持自然语言，留空则导入全部）',
    chapterRangePh: '例如：从第3章微分方程到非线性微分方程通解\n或：第3章和第4章全部内容',
    genTocStructure: '✨ 生成目录结构',
    cancelBack: '✕ 取消并返回',
    stepCancel: '取消', nextStep: '下一步 →',
    selectChapterRange: '选择章节范围',
    selectRange: '选择范围',
    rangeStartPh: '起始  如 3.1', rangeTo: '至', rangeEndPh: '结束  如 7.8',
    applyRange: '应用', selectAll: '全选', clearAll: '清空',
    selectedChaps: '已选 {chaps} 个章节 / {secs} 个小节',
    prevStep: '← 上一步', importSelected: '导入选中章节',
    editCourseTitle: '编辑课程信息',
    manualModalTitle: '手动添加章节',
    manualHint: '每行一个章节或小节，用数字前缀表示层级：',
    manualPh: '例：\n第三章 线性代数\n3.1 向量空间\n3.2 子空间\n第四章 矩阵运算\n4.1 矩阵加法',
    viewEdit: '查看 / 编辑', renameBtn: '✎ 重命名',
    newFilenamePh: '输入新文件名',
    renameFile: '重命名文件', newFilename: '新文件名', confirmRename: '确认重命名',
    aiParsing: 'AI 解析中', aiParseTask: '🤖 AI 解析任务', collapsePanel: '▲ 收起',
    aiDone: '任务已完成', tasksInProgress: '{n} 个任务进行中',
    courseLabel: '课程', subjectMetaLabel: '科目', countdown: '倒计时',
    viewFile: '查看', deleteFile: '删除',
    deleted: '已删除', renamed: '已重命名 ✓', saved: '已保存 ✓',
    savedMaterials: '已保存到课程资料 ✓',
    configToc: '配置目录 →',
    parseChapError: '未能解析出章节，请检查格式',
    parseFormatError: '未能解析，请检查格式',
    rangeSelected: '已选范围 {start}  至  {end}',
    selectAtLeastOne: '请至少选择一个章节',
    importedChaps: '已导入 {n} 个章节 ✓',
    addedChaps: '已添加 {n} 个章节 ✓',
    uploadedFiles: '已上传 {n} 个文件',
    convertingToMd: '→ 正在转换为 Markdown…',
    courseUpdated: '课程信息已更新 ✓',
    chaptersCleared: '目录已清空，可重新导入',
    enterUrl: '请输入链接',
    savedMdFile: '已保存 Markdown 资料：{name} ✓',
    pdfExtractFailed: 'PDF 提取失败：',
    langLabel: '语言',
  },
  en: {
    appName: 'Study Tracker', pageTitle: 'Exam Study Tracker',
    myCourses: 'My Courses', addCourse: 'Add Course',
    noCoursesTitle: 'No courses yet', noCoursesHint: 'Click "Add Course" to start planning your study sessions',
    addCourseTitle: 'Add New Course', courseName: 'Course Name', courseNamePh: 'e.g. Calculus II',
    subjectLabel: 'Category', subjectPh: 'e.g. Math, English, Physics…',
    examDate: 'Exam Date', totalChapters: 'Total Chapters', totalChaptersPh: 'e.g. 12',
    color: 'Color',
    cancel: 'Cancel', add: 'Add', addCourseBtn: 'Add Course', saveChanges: 'Save Changes',
    openCourse: 'Open Course', deleteCourse: 'Delete Course',
    noDate: 'No exam date', expired: 'Expired', examToday: 'Exam today!',
    daysLeft: '{n} days left',
    studyProgress: 'Progress', chaptersCount: '{done}/{total} chapters',
    totalCoursesCount: '{n} courses', avgProgressText: 'Avg. Progress {n}%',
    courseAdded: '"{name}" added ✓', courseDeleted: '"{name}" deleted',
    backBtn: '← Back', editInfo: '✎ Edit Info', importChapters: '+ Import Chapters',
    loading: 'Loading…',
    totalProgress: 'Total Progress',
    noChapters: 'No chapters',
    noChaptersAddHint: 'No chapters — import or add manually',
    heroCompleted: '{done} / {total} topics completed',
    chapterToc: 'Chapters',
    noChaptersImport: 'No chapters — click to import',
    chapMeta: '{n} chapters · {pts} topics',
    secCount: '{n} topics',
    importFromPdfTitle: 'Import Chapters from PDF',
    importPdfDrag: 'Drag your textbook PDF here, or click to select a file',
    choosePdf: 'Choose PDF File',
    manualAdd: 'Add Chapters Manually',
    courseMaterials: 'Course Materials',
    pdfConvert: 'PDF Convert',
    htmlConvert: 'HTML Convert',
    htmlConvertTitle: 'Upload HTML file and convert to Markdown via MinerU',
    dragToUpload: 'Drag files here or click to upload',
    importMore: '+ Import More',
    noChaptersMore: 'No chapters — click "Import More" above',
    expandAll: 'Expand', collapseAll: 'Collapse', resetChapters: 'Reset',
    aiAssistant: 'AI Study Assistant', aiSub: 'I can help you create study plans, answer questions, and analyze key content.',
    genPlan: '📋 Generate Study Plan', summarize: '📖 Summarize Key Points', quiz: '❓ Quiz Me',
    askAI: 'Ask the AI assistant… (Enter to send, Shift+Enter for newline)',
    history: 'History', newChat: '＋ New Chat',
    historyChat: 'Chat History', historyBtnTitle: 'Chat History',
    aiContextTitle: 'Readable Markdown course materials',
    filesCount: '{n} files',
    tabText: 'Text', tabUrl: 'Link',
    guidePh: 'Paste study notes, exam highlights, question types…',
    uploadPdfHint: 'Upload a small PDF — AI will extract the text automatically',
    clearReselect: '✕ Re-select', fetchContent: 'Fetch', clearUrl: '✕ Clear',
    attachGuide: 'Attach study guide',
    aiInputHint: 'AI can read course Markdown materials · Enter to send',
    delConv: 'Delete',
    importPdfModalTitle: 'Import PDF Contents',
    dropPdfHere: 'Drop PDF here', orText: 'or', chooseFile: 'Choose File',
    pdfBookmarkNote: 'Only PDFs with a bookmark outline are supported',
    extractingToc: 'Extracting contents, please wait…',
    retrySelect: 'Try Again', noBookmarkTitle: 'This PDF has no bookmark outline',
    pasteTocLabel: 'Paste Contents Text',
    tocPastePh: 'e.g.:\nChapter 3 Linear Algebra\n3.1 Vector Spaces\n3.2 Subspaces\n3.3 Linear Independence\nChapter 4 Matrix Operations\n4.1 Matrix Addition',
    parseTocText: 'Parse Text', orUseAI: 'or use AI extraction',
    mineruDesc: 'Parse PDF via MinerU, then Gemini generates the chapter structure automatically',
    pdfSizeNote: '(Supports PDFs up to 3.5 MB)',
    aiExtractToc: '🤖 AI Extract Contents',
    uploadFile: 'Upload', mineruParse: 'MinerU Parse', generateToc: 'Generate',
    preparing: 'Preparing…',
    chapterRangeLabel: 'Describe the chapter range to import (natural language, leave blank for all)',
    chapterRangePh: 'e.g.: From Chapter 3 Differential Equations to nonlinear ODEs\nor: All content in Chapters 3 and 4',
    genTocStructure: '✨ Generate Structure',
    cancelBack: '✕ Cancel & Back',
    stepCancel: 'Cancel', nextStep: 'Next →',
    selectChapterRange: 'Select Chapter Range',
    selectRange: 'Range',
    rangeStartPh: 'Start  e.g. 3.1', rangeTo: 'to', rangeEndPh: 'End  e.g. 7.8',
    applyRange: 'Apply', selectAll: 'Select All', clearAll: 'Clear',
    selectedChaps: '{chaps} chapters / {secs} sections selected',
    prevStep: '← Back', importSelected: 'Import Selected',
    editCourseTitle: 'Edit Course Info',
    manualModalTitle: 'Add Chapters Manually',
    manualHint: 'One chapter or section per line; use a numeric prefix for hierarchy:',
    manualPh: 'e.g.:\nChapter 3 Linear Algebra\n3.1 Vector Spaces\n3.2 Subspaces\nChapter 4 Matrix Operations\n4.1 Matrix Addition',
    viewEdit: 'View / Edit', renameBtn: '✎ Rename',
    newFilenamePh: 'Enter new filename',
    renameFile: 'Rename File', newFilename: 'New Filename', confirmRename: 'Confirm Rename',
    aiParsing: 'AI Parsing', aiParseTask: '🤖 AI Parse Tasks', collapsePanel: '▲ Collapse',
    aiDone: 'Done', tasksInProgress: '{n} tasks in progress',
    courseLabel: 'Course', subjectMetaLabel: 'Subject', countdown: 'Countdown',
    viewFile: 'View', deleteFile: 'Delete',
    deleted: 'Deleted', renamed: 'Renamed ✓', saved: 'Saved ✓',
    savedMaterials: 'Saved to course materials ✓',
    configToc: 'Configure Chapters →',
    parseChapError: 'Could not parse chapters — check format',
    parseFormatError: 'Could not parse — check format',
    rangeSelected: 'Range: {start} to {end}',
    selectAtLeastOne: 'Select at least one chapter',
    importedChaps: '{n} chapters imported ✓',
    addedChaps: '{n} chapters added ✓',
    uploadedFiles: '{n} files uploaded',
    convertingToMd: '→ converting to Markdown…',
    courseUpdated: 'Course info updated ✓',
    chaptersCleared: 'Chapters cleared — you can re-import',
    enterUrl: 'Please enter a URL',
    savedMdFile: 'Markdown saved: {name} ✓',
    pdfExtractFailed: 'PDF extraction failed: ',
    langLabel: 'Language',
  },
  es: {
    appName: 'Seguidor de Estudio', pageTitle: 'Seguidor de Exámenes',
    myCourses: 'Mis Cursos', addCourse: 'Agregar Curso',
    noCoursesTitle: 'Aún no hay cursos', noCoursesHint: 'Haz clic en "Agregar Curso" para comenzar a planificar',
    addCourseTitle: 'Agregar Nuevo Curso', courseName: 'Nombre del Curso', courseNamePh: 'Ej: Cálculo II',
    subjectLabel: 'Categoría', subjectPh: 'Ej: Matemáticas, Inglés, Física…',
    examDate: 'Fecha del Examen', totalChapters: 'Total de Capítulos', totalChaptersPh: 'Ej: 12',
    color: 'Color',
    cancel: 'Cancelar', add: 'Agregar', addCourseBtn: 'Agregar Curso', saveChanges: 'Guardar Cambios',
    openCourse: 'Abrir Curso', deleteCourse: 'Eliminar Curso',
    noDate: 'Sin fecha de examen', expired: 'Expirado', examToday: '¡Examen hoy!',
    daysLeft: 'Quedan {n} días',
    studyProgress: 'Progreso', chaptersCount: '{done}/{total} capítulos',
    totalCoursesCount: '{n} cursos', avgProgressText: 'Progreso Prom. {n}%',
    courseAdded: '"{name}" agregado ✓', courseDeleted: '"{name}" eliminado',
    backBtn: '← Volver', editInfo: '✎ Editar Info', importChapters: '+ Importar Capítulos',
    loading: 'Cargando…',
    totalProgress: 'Progreso Total',
    noChapters: 'Sin capítulos',
    noChaptersAddHint: 'Sin capítulos — importa o agrega manualmente',
    heroCompleted: '{done} / {total} temas completados',
    chapterToc: 'Capítulos',
    noChaptersImport: 'Sin capítulos — clic para importar',
    chapMeta: '{n} capítulos · {pts} temas',
    secCount: '{n} temas',
    importFromPdfTitle: 'Importar Capítulos desde PDF',
    importPdfDrag: 'Arrastra tu PDF aquí, o haz clic para seleccionar un archivo',
    choosePdf: 'Elegir Archivo PDF',
    manualAdd: 'Agregar Capítulos Manualmente',
    courseMaterials: 'Materiales del Curso',
    pdfConvert: 'Convertir PDF',
    htmlConvert: 'Convertir HTML',
    htmlConvertTitle: 'Subir archivo HTML y convertir a Markdown vía MinerU',
    dragToUpload: 'Arrastra archivos aquí o haz clic para subir',
    importMore: '+ Importar Más',
    noChaptersMore: 'Sin capítulos — haz clic en "Importar Más"',
    expandAll: 'Expandir', collapseAll: 'Colapsar', resetChapters: 'Reiniciar',
    aiAssistant: 'Asistente de Estudio IA', aiSub: 'Puedo ayudarte a crear planes de estudio, responder preguntas y analizar contenido clave.',
    genPlan: '📋 Generar Plan de Estudio', summarize: '📖 Resumir Puntos Clave', quiz: '❓ Hacerme Preguntas',
    askAI: 'Pregunta al asistente IA… (Enter para enviar)',
    history: 'Historial', newChat: '＋ Nueva Conversación',
    historyChat: 'Historial de Chat', historyBtnTitle: 'Historial de Chat',
    aiContextTitle: 'Materiales del curso en Markdown disponibles',
    filesCount: '{n} archivos',
    tabText: 'Texto', tabUrl: 'Enlace',
    guidePh: 'Pega notas de estudio, puntos clave del examen, tipos de preguntas…',
    uploadPdfHint: 'Sube un PDF pequeño — la IA extraerá el texto automáticamente',
    clearReselect: '✕ Volver a seleccionar', fetchContent: 'Obtener', clearUrl: '✕ Limpiar',
    attachGuide: 'Adjuntar guía de estudio',
    aiInputHint: 'La IA puede leer materiales Markdown del curso · Enter para enviar',
    delConv: 'Eliminar',
    importPdfModalTitle: 'Importar PDF',
    dropPdfHere: 'Suelta el PDF aquí', orText: 'o', chooseFile: 'Elegir Archivo',
    pdfBookmarkNote: 'Solo se admiten PDFs con marcadores de índice',
    extractingToc: 'Extrayendo contenido, por favor espera…',
    retrySelect: 'Reintentar', noBookmarkTitle: 'Este PDF no tiene marcadores de índice',
    pasteTocLabel: 'Pegar Texto del Índice',
    tocPastePh: 'Ej:\nCapítulo 3 Álgebra Lineal\n3.1 Espacios Vectoriales\n3.2 Subespacios\n3.3 Independencia Lineal\nCapítulo 4 Operaciones con Matrices\n4.1 Suma de Matrices',
    parseTocText: 'Analizar Texto', orUseAI: 'o usar extracción con IA',
    mineruDesc: 'Analiza el PDF con MinerU, luego Gemini genera la estructura de capítulos automáticamente',
    pdfSizeNote: '(Compatible con PDFs de hasta 3.5 MB)',
    aiExtractToc: '🤖 Extraer con IA',
    uploadFile: 'Subir', mineruParse: 'Análisis MinerU', generateToc: 'Generar',
    preparing: 'Preparando…',
    chapterRangeLabel: 'Describe el rango de capítulos a importar (lenguaje natural, vacío = todo)',
    chapterRangePh: 'Ej: Del Capítulo 3 Ecuaciones Diferenciales hasta las EDOs no lineales\no: Todo el contenido de los Capítulos 3 y 4',
    genTocStructure: '✨ Generar Estructura',
    cancelBack: '✕ Cancelar y Volver',
    stepCancel: 'Cancelar', nextStep: 'Siguiente →',
    selectChapterRange: 'Seleccionar Rango',
    selectRange: 'Rango',
    rangeStartPh: 'Inicio  ej. 3.1', rangeTo: 'hasta', rangeEndPh: 'Fin  ej. 7.8',
    applyRange: 'Aplicar', selectAll: 'Seleccionar Todo', clearAll: 'Limpiar',
    selectedChaps: '{chaps} capítulos / {secs} secciones seleccionados',
    prevStep: '← Anterior', importSelected: 'Importar Seleccionados',
    editCourseTitle: 'Editar Curso',
    manualModalTitle: 'Agregar Capítulos Manualmente',
    manualHint: 'Un capítulo o sección por línea; usa prefijo numérico para jerarquía:',
    manualPh: 'Ej:\nCapítulo 3 Álgebra Lineal\n3.1 Espacios Vectoriales\n3.2 Subespacios\nCapítulo 4 Operaciones con Matrices\n4.1 Suma de Matrices',
    viewEdit: 'Ver / Editar', renameBtn: '✎ Renombrar',
    newFilenamePh: 'Ingresa el nuevo nombre de archivo',
    renameFile: 'Renombrar Archivo', newFilename: 'Nuevo Nombre', confirmRename: 'Confirmar Renombre',
    aiParsing: 'IA Analizando', aiParseTask: '🤖 Tareas de IA', collapsePanel: '▲ Colapsar',
    aiDone: 'Completado', tasksInProgress: '{n} tareas en progreso',
    courseLabel: 'Curso', subjectMetaLabel: 'Asignatura', countdown: 'Cuenta Regresiva',
    viewFile: 'Ver', deleteFile: 'Eliminar',
    deleted: 'Eliminado', renamed: 'Renombrado ✓', saved: 'Guardado ✓',
    savedMaterials: 'Guardado en materiales ✓',
    configToc: 'Configurar Capítulos →',
    parseChapError: 'No se pudo analizar — verifica el formato',
    parseFormatError: 'No se pudo analizar — verifica el formato',
    rangeSelected: 'Rango: {start} a {end}',
    selectAtLeastOne: 'Selecciona al menos un capítulo',
    importedChaps: '{n} capítulos importados ✓',
    addedChaps: '{n} capítulos agregados ✓',
    uploadedFiles: '{n} archivos subidos',
    convertingToMd: '→ convirtiendo a Markdown…',
    courseUpdated: 'Info del curso actualizada ✓',
    chaptersCleared: 'Capítulos borrados — puedes volver a importar',
    enterUrl: 'Por favor ingresa un enlace',
    savedMdFile: 'Markdown guardado: {name} ✓',
    pdfExtractFailed: 'Error al extraer PDF: ',
    langLabel: 'Idioma',
  }
};

window.t = function(key) {
  var lang = localStorage.getItem('app_lang') || 'zh';
  return (STRINGS[lang] && STRINGS[lang][key]) || STRINGS.zh[key] || key;
};

window.tf = function(key, vars) {
  var s = window.t(key);
  if (vars) Object.keys(vars).forEach(function(k) { s = s.replace('{' + k + '}', vars[k]); });
  return s;
};

window.applyStrings = function() {
  document.querySelectorAll('[data-i18n]').forEach(function(el) { el.textContent = window.t(el.dataset.i18n); });
  document.querySelectorAll('[data-i18n-ph]').forEach(function(el) { el.placeholder = window.t(el.dataset.i18nPh); });
  document.querySelectorAll('[data-i18n-title]').forEach(function(el) { el.title = window.t(el.dataset.i18nTitle); });
  var lang = localStorage.getItem('app_lang') || 'zh';
  document.documentElement.lang = lang === 'zh' ? 'zh-CN' : lang === 'es' ? 'es' : 'en';
};
